title: Rom Hack Studios
description: Download the latest Emerald Crest patch here.
theme: just-the-docs

url: https://romhackstudios.github.io/

aux_links:
  Discord: https://discord.gg/aaghat-s-server-965900074532081674
